### ISSUE TITLE
Weird issue on ajax content

### ISSUE THREAD

**Issue by alegemaate** [alegemaate/nonoreplace#9]
![image](https://user-images.githubusercontent.com/9920336/49178893-ffbdd700-f31e-11e8-84f3-0528cefd770d.png)

**Comment by alegemaate** [comment]
![image](https://user-images.githubusercontent.com/9920336/49179055-6fcc5d00-f31f-11e8-9a96-538dfca73967.png)

**Comment by justin-gerhardt** [comment]
What was the replacement mapping?

**Comment by justin-gerhardt** [comment]
It would be pretty simple to just not replace inputs. Is that the only place you are getting the issue?

**Comment by alegemaate** [comment]
Fixed, instead of doing replacements on textcontent, passed entire new mutator
```
for (let mut of mutationsList) {
  doRecursiveReplace(mut.target, replacements);
}
```

**Comment by alegemaate** [comment]
![image](https://user-images.githubusercontent.com/9920336/49180919-069b1880-f324-11e8-9e51-3323d2ae4ac6.png)

**Comment by justin-gerhardt** [comment]
Ddoing a recursive replace will increase the performance penalty. However text node don't normally have deep or wide child hierarchys.

**Comment by alegemaate** [comment]
This is true, it is still lightning fast, but of course less efficient. It may have to do for now.
